POST http://localhost:3000/post HTTP/1.1	
content-type: application/json	

{	
    "studentID":"18-19200",
    "studentName":"Job",
    "gradeList":[
        {"name":"KAPCUL2", "grade":1},
         {"name":"MATH3", "grade":2},
         {"name":"COMSCi", "grade":1}
        
    ]	
}
###
PATCH http://localhost:3000/update/61f3cde8a35d092418bdc743 HTTP/1.1	
content-type: application/json

{	
    "studentID":"18-19200",
    "studentName":"Joboooooooo",
    "gradeList":[
        {"name":"KAPCUL2", "grade":1000},
         {"name":"MATH3", "grade":200},
         {"name":"COMSCi", "grade":100}
        
    ]	
}
###
GET http://localhost:3000/ HTTP/1.1
###

GET http://localhost:3000/601558be348ea827c4381496 HTTP/1.1
###

DELETE http://localhost:3000/remove/601558be348ea827c4381496 HTTP/1.1
