POST http://localhost:3000/post HTTP/1.1	
content-type: application/json	

{	
    "studentID":"18-19983",
    "studentName":"Joshua",
    "gradeList":[
        {"name":"KAPCUL", "grade":1},
         {"name":"MATH", "grade":1},
         {"name":"PHY", "grade":3}
        
    ]	
}
###
PATCH http://localhost:3000/update/601558be348ea827c4381496 HTTP/1.1	
content-type: application/json	

{	
    "title": "LOdsdsdsRDDDDDDDDDDDD",	
    "content":"fdfdkf",	
    "author":"Sangalang-2-2"	
}
###
GET http://localhost:3000/ HTTP/1.1
###

GET http://localhost:3000/601558be348ea827c4381496 HTTP/1.1
###

DELETE http://localhost:3000/remove/601558be348ea827c4381496 HTTP/1.1
