POST http://localhost:3000/post HTTP/1.1
content-type: application/json
{
    "studentID":"18-1983",
    "studentName":"Joshua",
    "gradeList":[
        {"name":"KAPCUL", "grade":1},
         {"name":"MATH", "grade":1}
        
    ]
    
}